'use client';

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { expenseData } from '@/lib/data';
import { IndianRupee, FileDown } from 'lucide-react';
import { Button } from '../ui/button';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export function ExpenseReport() {
  const totalExpenses = expenseData.reduce((acc, expense) => {
    const amount = Number(String(expense.amount).replace(/[^0-9.-]+/g, ''));
    return acc + amount;
  }, 0);

  const expensesByCategory = expenseData.reduce((acc, expense) => {
    const category = expense.category;
    const amount = Number(String(expense.amount).replace(/[^0-9.-]+/g, ''));
    if (!acc[category]) {
      acc[category] = 0;
    }
    acc[category] += amount;
    return acc;
  }, {} as Record<string, number>);

  const topCategory =
    Object.entries(expensesByCategory).sort((a, b) => b[1] - a[1])[0] || ['N/A', 0];

  const handleExport = () => {
    const doc = new jsPDF();
    const tableData = expenseData.map(e => [e.category, e.item, e.amount, e.date]);
    const tableHead = [['Category', 'Item/Description', 'Amount', 'Date']];
    const generationDate = new Date().toLocaleDateString('en-IN', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    // Header
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('QuarryFlow', 15, 20);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Expense Report', 15, 26);
    doc.text(`Generated on: ${generationDate}`, 200, 26, { align: 'right' });
    doc.line(15, 30, 200, 30); // Horizontal line

    // Summary Section
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Summary', 15, 40);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Expenses: ₹${totalExpenses.toLocaleString('en-IN')}`, 15, 48);
    doc.text(`Top Expense Category: ${topCategory[0]} (₹${topCategory[1].toLocaleString('en-IN')})`, 15, 54);

    // Table
    (doc as any).autoTable({
      head: tableHead,
      body: tableData,
      startY: 65,
      theme: 'grid',
      headStyles: {
        fillColor: [41, 128, 185], // A shade of blue
        textColor: 255,
        fontStyle: 'bold',
      },
      didDrawPage: (data: any) => {
        // Footer
        const pageCount = doc.getNumberOfPages();
        doc.setFontSize(8);
        doc.text(
          `Page ${data.pageNumber} of ${pageCount}`,
          data.settings.margin.left,
          doc.internal.pageSize.height - 10
        );
        doc.text(
          'Generated by QuarryFlow',
          doc.internal.pageSize.width - data.settings.margin.right,
          doc.internal.pageSize.height - 10,
          { align: 'right' }
        );
      },
    });

    doc.save('QuarryFlow_Expense_Report.pdf');
  };


  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <div>
          <CardTitle className="font-headline">Expense Report</CardTitle>
          <CardDescription>A summary of your business expenses.</CardDescription>
        </div>
        <Button onClick={handleExport}>
          <FileDown className="mr-2 h-4 w-4" />
          Export as PDF
        </Button>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="grid gap-4 md:grid-cols-2">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Total Expenses</CardTitle>
              <IndianRupee className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">
                ₹{totalExpenses.toLocaleString('en-IN')}
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">
                Top Expense Category
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{topCategory[0]}</div>
              <p className="text-xs text-muted-foreground">
                ₹{topCategory[1].toLocaleString('en-IN')}
              </p>
            </CardContent>
          </Card>
        </div>

        <div className="space-y-2">
          <h3 className="text-lg font-semibold">Expense Breakdown</h3>
          <Card>
            <CardContent className="pt-6">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Category</TableHead>
                    <TableHead>Item</TableHead>
                    <TableHead>Amount</TableHead>
                    <TableHead>Date</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {expenseData.map(expense => (
                    <TableRow key={expense.id}>
                      <TableCell className="font-medium">
                        {expense.category}
                      </TableCell>
                      <TableCell>{expense.item}</TableCell>
                      <TableCell>{expense.amount}</TableCell>
                      <TableCell>{expense.date}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
      </CardContent>
    </Card>
  );
}
